server:
  port: 8091

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}

appDescription: "Pokedex API"
appVersion: "1.0.0"

#swagger http://localhost:8091/swagger-ui/index.html

springdoc:
  swagger-ui:
    path: /index.html